apiVersion: v1
kind: Pod
metadata:
  name: svc1
  labels:
    app: svc1
spec:
  containers:
    - image: aint/svc1:latest
      imagePullPolicy: IfNotPresent
      name: svc1
      ports:
        - containerPort: 8080