apiVersion: v1
kind: Pod
metadata:
  name: svc2
  labels:
    app: svc2
spec:
  containers:
    - image: aint/svc2:latest
      imagePullPolicy: IfNotPresent
      name: svc2
      ports:
        - containerPort: 8081